#include<stdio.h>

int main()
{
    int x,y,z,i,j,n;
    scanf("%d %d %d",&x,&y,&z);
    printf("\n");
    int a[x][x],b[y][y],c[z][z];
    int d[2*x+2],e[2*y+2],f[2*z+2];
    for(i=0;i<2*x+2;i++)
        d[i]=0;
    for(i=0;i<x;i++)
    {
        for(j=0;j<x;j++)
        {
            scanf("%d",&a[i][j]);
        }
    }
    printf("\n");
    for(i=0;i<2*y+2;i++)
        e[i]=0;
    for(i=0;i<y;i++)
    {
        for(j=0;j<y;j++)
        {
            scanf("%d",&b[i][j]);
        }
    }
    printf("\n");
    for(i=0;i<2*z+2;i++)
        f[i]=0;
    for(i=0;i<z;i++)
    {
        for(j=0;j<z;j++)
        {
            scanf("%d",&c[i][j]);
        }
    }
    printf("\n");
    n=0;
    for(i=0;i<x;i++)
    {
        for(j=0;j<x;j++)
        {
            d[n]+=a[i][j];
            d[n+x]+=a[j][i];
        }
        n++;
        d[2*x]+=a[i][i];
        d[2*x+1]+=a[i][x-i-1];
    }
    n=0;
    for(i=0;i<y;i++)
    {
        for(j=0;j<y;j++)
        {
            e[n]+=b[i][j];
            e[n+y]+=b[j][i];
        }
        n++;
        e[2*y]+=b[i][i];
        e[2*y+1]+=b[i][y-i-1];
    }
    n=0;
    for(i=0;i<z;i++)
    {
        for(j=0;j<z;j++)
        {
            f[n]+=c[i][j];
            f[n+z]+=c[j][i];
        }
        n++;
        f[2*z]+=c[i][i];
        f[2*z+1]+=c[i][z-i-1];
    }
    /*for(i=0;i<2*x+2;i++)
        printf("%d\n",d[i]);
    for(i=0;i<2*y+2;i++)
        printf("%d\n",e[i]);
    for(i=0;i<2*z+2;i++)
        printf("%d\n",f[i]);*/
    for(i=0;i<2*x+2;i++)
    {
        if(d[i]!=d[i+1]&&i!=2*x+1)
        {
            printf("yes\n");
            break;
        }
    }
    if(i==2*x+2)
        printf("no\n");
    for(i=0;i<2*y+2;i++)
    {
        if(e[i]!=e[i+1]&&i!=2*y+1)
        {
            printf("yes\n");
            break;
        }
    }
    if(i==2*y+2)
        printf("no\n");
    for(i=0;i<2*z+2;i++)
    {
        if(f[i]!=f[i+1]&&i!=2*z+1)
        {
            printf("yes");
            break;
        }
    }
    if(i==2*z+2)
        printf("no");
    return 0;
}
